var data = {
    "name":[ "Audi e-tron", "Audi A1", "Audi A4", "Audi A5", "Audi A6", "Audi A7", "Audi A8", "Audi Q2", "Audi Q3", "Audi Q5", "Audi Q7", "Audi Q8", "Audi TT"],
    "car":[
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus velit, semper non elit sit amet, pretium viverra lacus. Maecenas ornare lorem ac lacus ultricies, vel congue sem accumsan. Curabitur venenatis massa mauris, consectetur tempus mi euismod sit amet. Vestibulum sagittis erat vel nisl euismod, eget fringilla purus iaculis. Suspendisse metus ligula, imperdiet sed mi in, mattis mattis sapien. Vivamus in interdum lorem, nec sodales justo. Curabitur ut sodales ex, ut finibus felis. Sed ultricies diam at sapien egestas, eget tempus purus feugiat. Sed suscipit efficitur ex, at ullamcorper urna ornare nec. Etiam eget cursus odio. Praesent tempor aliquam metus quis semper. Vivamus ligula quam, rhoncus eget enim posuere, blandit auctor dui. In hac habitasse platea dictumst. Aenean sollicitudin lacinia nisi, a efficitur orci rhoncus posuere. Maecenas faucibus ac arcu ut ornare.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus velit, semper non elit sit amet, pretium viverra lacus. Maecenas ornare lorem ac lacus ultricies, vel congue sem accumsan. Curabitur venenatis massa mauris, consectetur tempus mi euismod sit amet. Vestibulum sagittis erat vel nisl euismod, eget fringilla purus iaculis. Suspendisse metus ligula, imperdiet sed mi in, mattis mattis sapien. Vivamus in interdum lorem, nec sodales justo. Curabitur ut sodales ex, ut finibus felis. Sed ultricies diam at sapien egestas, eget tempus purus feugiat. Sed suscipit efficitur ex, at ullamcorper urna ornare nec. Etiam eget cursus odio. Praesent tempor aliquam metus quis semper. Vivamus ligula quam, rhoncus eget enim posuere, blandit auctor dui. In hac habitasse platea dictumst. Aenean sollicitudin lacinia nisi, a efficitur orci rhoncus posuere. Maecenas faucibus ac arcu ut ornare.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus velit, semper non elit sit amet, pretium viverra lacus. Maecenas ornare lorem ac lacus ultricies, vel congue sem accumsan. Curabitur venenatis massa mauris, consectetur tempus mi euismod sit amet. Vestibulum sagittis erat vel nisl euismod, eget fringilla purus iaculis. Suspendisse metus ligula, imperdiet sed mi in, mattis mattis sapien. Vivamus in interdum lorem, nec sodales justo. Curabitur ut sodales ex, ut finibus felis. Sed ultricies diam at sapien egestas, eget tempus purus feugiat. Sed suscipit efficitur ex, at ullamcorper urna ornare nec. Etiam eget cursus odio. Praesent tempor aliquam metus quis semper. Vivamus ligula quam, rhoncus eget enim posuere, blandit auctor dui. In hac habitasse platea dictumst. Aenean sollicitudin lacinia nisi, a efficitur orci rhoncus posuere. Maecenas faucibus ac arcu ut ornare.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus velit, semper non elit sit amet, pretium viverra lacus. Maecenas ornare lorem ac lacus ultricies, vel congue sem accumsan. Curabitur venenatis massa mauris, consectetur tempus mi euismod sit amet. Vestibulum sagittis erat vel nisl euismod, eget fringilla purus iaculis. Suspendisse metus ligula, imperdiet sed mi in, mattis mattis sapien. Vivamus in interdum lorem, nec sodales justo. Curabitur ut sodales ex, ut finibus felis. Sed ultricies diam at sapien egestas, eget tempus purus feugiat. Sed suscipit efficitur ex, at ullamcorper urna ornare nec. Etiam eget cursus odio. Praesent tempor aliquam metus quis semper. Vivamus ligula quam, rhoncus eget enim posuere, blandit auctor dui. In hac habitasse platea dictumst. Aenean sollicitudin lacinia nisi, a efficitur orci rhoncus posuere. Maecenas faucibus ac arcu ut ornare.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus velit, semper non elit sit amet, pretium viverra lacus. Maecenas ornare lorem ac lacus ultricies, vel congue sem accumsan. Curabitur venenatis massa mauris, consectetur tempus mi euismod sit amet. Vestibulum sagittis erat vel nisl euismod, eget fringilla purus iaculis. Suspendisse metus ligula, imperdiet sed mi in, mattis mattis sapien. Vivamus in interdum lorem, nec sodales justo. Curabitur ut sodales ex, ut finibus felis. Sed ultricies diam at sapien egestas, eget tempus purus feugiat. Sed suscipit efficitur ex, at ullamcorper urna ornare nec. Etiam eget cursus odio. Praesent tempor aliquam metus quis semper. Vivamus ligula quam, rhoncus eget enim posuere, blandit auctor dui. In hac habitasse platea dictumst. Aenean sollicitudin lacinia nisi, a efficitur orci rhoncus posuere. Maecenas faucibus ac arcu ut ornare.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus velit, semper non elit sit amet, pretium viverra lacus. Maecenas ornare lorem ac lacus ultricies, vel congue sem accumsan. Curabitur venenatis massa mauris, consectetur tempus mi euismod sit amet. Vestibulum sagittis erat vel nisl euismod, eget fringilla purus iaculis. Suspendisse metus ligula, imperdiet sed mi in, mattis mattis sapien. Vivamus in interdum lorem, nec sodales justo. Curabitur ut sodales ex, ut finibus felis. Sed ultricies diam at sapien egestas, eget tempus purus feugiat. Sed suscipit efficitur ex, at ullamcorper urna ornare nec. Etiam eget cursus odio. Praesent tempor aliquam metus quis semper. Vivamus ligula quam, rhoncus eget enim posuere, blandit auctor dui. In hac habitasse platea dictumst. Aenean sollicitudin lacinia nisi, a efficitur orci rhoncus posuere. Maecenas faucibus ac arcu ut ornare.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus velit, semper non elit sit amet, pretium viverra lacus. Maecenas ornare lorem ac lacus ultricies, vel congue sem accumsan. Curabitur venenatis massa mauris, consectetur tempus mi euismod sit amet. Vestibulum sagittis erat vel nisl euismod, eget fringilla purus iaculis. Suspendisse metus ligula, imperdiet sed mi in, mattis mattis sapien. Vivamus in interdum lorem, nec sodales justo. Curabitur ut sodales ex, ut finibus felis. Sed ultricies diam at sapien egestas, eget tempus purus feugiat. Sed suscipit efficitur ex, at ullamcorper urna ornare nec. Etiam eget cursus odio. Praesent tempor aliquam metus quis semper. Vivamus ligula quam, rhoncus eget enim posuere, blandit auctor dui. In hac habitasse platea dictumst. Aenean sollicitudin lacinia nisi, a efficitur orci rhoncus posuere. Maecenas faucibus ac arcu ut ornare.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus velit, semper non elit sit amet, pretium viverra lacus. Maecenas ornare lorem ac lacus ultricies, vel congue sem accumsan. Curabitur venenatis massa mauris, consectetur tempus mi euismod sit amet. Vestibulum sagittis erat vel nisl euismod, eget fringilla purus iaculis. Suspendisse metus ligula, imperdiet sed mi in, mattis mattis sapien. Vivamus in interdum lorem, nec sodales justo. Curabitur ut sodales ex, ut finibus felis. Sed ultricies diam at sapien egestas, eget tempus purus feugiat. Sed suscipit efficitur ex, at ullamcorper urna ornare nec. Etiam eget cursus odio. Praesent tempor aliquam metus quis semper. Vivamus ligula quam, rhoncus eget enim posuere, blandit auctor dui. In hac habitasse platea dictumst. Aenean sollicitudin lacinia nisi, a efficitur orci rhoncus posuere. Maecenas faucibus ac arcu ut ornare.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus velit, semper non elit sit amet, pretium viverra lacus. Maecenas ornare lorem ac lacus ultricies, vel congue sem accumsan. Curabitur venenatis massa mauris, consectetur tempus mi euismod sit amet. Vestibulum sagittis erat vel nisl euismod, eget fringilla purus iaculis. Suspendisse metus ligula, imperdiet sed mi in, mattis mattis sapien. Vivamus in interdum lorem, nec sodales justo. Curabitur ut sodales ex, ut finibus felis. Sed ultricies diam at sapien egestas, eget tempus purus feugiat. Sed suscipit efficitur ex, at ullamcorper urna ornare nec. Etiam eget cursus odio. Praesent tempor aliquam metus quis semper. Vivamus ligula quam, rhoncus eget enim posuere, blandit auctor dui. In hac habitasse platea dictumst. Aenean sollicitudin lacinia nisi, a efficitur orci rhoncus posuere. Maecenas faucibus ac arcu ut ornare.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus velit, semper non elit sit amet, pretium viverra lacus. Maecenas ornare lorem ac lacus ultricies, vel congue sem accumsan. Curabitur venenatis massa mauris, consectetur tempus mi euismod sit amet. Vestibulum sagittis erat vel nisl euismod, eget fringilla purus iaculis. Suspendisse metus ligula, imperdiet sed mi in, mattis mattis sapien. Vivamus in interdum lorem, nec sodales justo. Curabitur ut sodales ex, ut finibus felis. Sed ultricies diam at sapien egestas, eget tempus purus feugiat. Sed suscipit efficitur ex, at ullamcorper urna ornare nec. Etiam eget cursus odio. Praesent tempor aliquam metus quis semper. Vivamus ligula quam, rhoncus eget enim posuere, blandit auctor dui. In hac habitasse platea dictumst. Aenean sollicitudin lacinia nisi, a efficitur orci rhoncus posuere. Maecenas faucibus ac arcu ut ornare.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus velit, semper non elit sit amet, pretium viverra lacus. Maecenas ornare lorem ac lacus ultricies, vel congue sem accumsan. Curabitur venenatis massa mauris, consectetur tempus mi euismod sit amet. Vestibulum sagittis erat vel nisl euismod, eget fringilla purus iaculis. Suspendisse metus ligula, imperdiet sed mi in, mattis mattis sapien. Vivamus in interdum lorem, nec sodales justo. Curabitur ut sodales ex, ut finibus felis. Sed ultricies diam at sapien egestas, eget tempus purus feugiat. Sed suscipit efficitur ex, at ullamcorper urna ornare nec. Etiam eget cursus odio. Praesent tempor aliquam metus quis semper. Vivamus ligula quam, rhoncus eget enim posuere, blandit auctor dui. In hac habitasse platea dictumst. Aenean sollicitudin lacinia nisi, a efficitur orci rhoncus posuere. Maecenas faucibus ac arcu ut ornare.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus velit, semper non elit sit amet, pretium viverra lacus. Maecenas ornare lorem ac lacus ultricies, vel congue sem accumsan. Curabitur venenatis massa mauris, consectetur tempus mi euismod sit amet. Vestibulum sagittis erat vel nisl euismod, eget fringilla purus iaculis. Suspendisse metus ligula, imperdiet sed mi in, mattis mattis sapien. Vivamus in interdum lorem, nec sodales justo. Curabitur ut sodales ex, ut finibus felis. Sed ultricies diam at sapien egestas, eget tempus purus feugiat. Sed suscipit efficitur ex, at ullamcorper urna ornare nec. Etiam eget cursus odio. Praesent tempor aliquam metus quis semper. Vivamus ligula quam, rhoncus eget enim posuere, blandit auctor dui. In hac habitasse platea dictumst. Aenean sollicitudin lacinia nisi, a efficitur orci rhoncus posuere. Maecenas faucibus ac arcu ut ornare.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras purus velit, semper non elit sit amet, pretium viverra lacus. Maecenas ornare lorem ac lacus ultricies, vel congue sem accumsan. Curabitur venenatis massa mauris, consectetur tempus mi euismod sit amet. Vestibulum sagittis erat vel nisl euismod, eget fringilla purus iaculis. Suspendisse metus ligula, imperdiet sed mi in, mattis mattis sapien. Vivamus in interdum lorem, nec sodales justo. Curabitur ut sodales ex, ut finibus felis. Sed ultricies diam at sapien egestas, eget tempus purus feugiat. Sed suscipit efficitur ex, at ullamcorper urna ornare nec. Etiam eget cursus odio. Praesent tempor aliquam metus quis semper. Vivamus ligula quam, rhoncus eget enim posuere, blandit auctor dui. In hac habitasse platea dictumst. Aenean sollicitudin lacinia nisi, a efficitur orci rhoncus posuere. Maecenas faucibus ac arcu ut ornare.",
    ]
}
    

//loop for cars
var eCar = document.getElementsByClassName("glider")[0];
for (let i = 1; i <= 13; i++) {
    eCar.innerHTML +=
        "<a id='data1' onclick='closing(" + i + ")' data-toggle='collapse' data-target='#car" + i + "' aria-controls='car" + i + "'\
                ria-expanded='false' data-parent='#data'>\
                <img id='pic"+ i + "' src='./Image+Site/first/2." + i + ".1.png' alt=''><p>" + data["name"][i-1] + "</p></a>";
}

//loop for data cars
var eData = document.getElementById("car");
for (let i = 1; i <= 13; i++) {
    eData.innerHTML +=
        '<div class="collapse border-top mt-3" id="car'+i+'" data-parent="#data">\
        <Button class="btn btn-dark rounded-circle my-4" data-toggle="collapse" data-target="#car'+i+'">X</Button>\
        <h5 class="font-weight-bolder">Audi e-tron</h5>\
        <p>'+ data["car"][i-1] +'</p></div>';

}

//closing function
function closing(i) {
    $("#car" + i + "").on("hide.bs.collapse", function () {
        $("#pic" + i + "").attr('src', './Image+Site/first/2.' + i + '.1.png');
    });
    $("#car" + i + "").on("show.bs.collapse", function () {
        $("#pic" + i + "").attr('src', './Image+Site/first/2.' + i + '.2.png');
    });
}

//glider function
window.addEventListener('load', function () {
    new Glider(document.querySelector('.glider'), {
        slidesToShow: 6.5,
        slidesToScroll: 6,
        arrows: {
            prev: '.glider-prev',
            next: '.glider-next'
        },
    });
})